//created on: 24-ago-2018
package photoBot.Drools.Reglas

//list any import classes here.
import photoBot.OpenCV.*;
import photoBot.Drools.*;
import photoBot.Gate.*;
import photoBot.Agentes.Comportamiento.*;
import photoBot.Imagen.*;


//declare any global variables here
global java.lang.Integer GR_BI;
global java.lang.Integer GR_PU;

/*rule "Solicitud de busqueda de todas las imagenes"
	salience 15
	when
		manejador : ManejadorReglas();
        grupoActivacion : Integer(grupoActivacion == GR_PU) from manejador.getGrupoActivado();
		
		etiqueta : Etiqueta();
        conversacion : Conversacion();
        comportamiento : ComportamientoAgenteConversacionUsuario();
        
        tipo_b : String (equals("Busqueda") == true) from etiqueta.getTipo();
    then
    	comportamiento.bot_solicitudBuscarTodasImagenes();  
    	
    	manejador.setGrupoActivado(ConstantesComportamiento.GRUPO_ESPERA_PETICION_USUARIO);
		update(manejador);
		
		System.out.println("REGLA BUSCAR TODAS LAS IMAGENES EJECUTADA");
end
*/

rule "Solicitud peticion busqueda imagenes"
salience 90
	when
		manejador : ManejadorReglas();
        grupoActivacion : Integer(grupoActivacion == GR_PU) from manejador.getGrupoActivado();
		
		etiqueta : Etiqueta();
        conversacion : Conversacion();
        comportamiento : ComportamientoAgenteConversacionUsuario();
        
        tipo_b : String (equals("Busqueda") == true) from etiqueta.getTipo();
    then
    	
    	manejador.setGrupoActivado(ConstantesComportamiento.GRUPO_BUSCAR_IMAGEN);
		update(manejador);
		
		System.out.println("REGLA SOLICITUD PETICION BUSQUEDA IMAGENES EJECUTADA");
end

rule "Obtener filtros de la conversacion"
salience 80
	when
		manejador : ManejadorReglas();
        grupoActivacion : Integer(grupoActivacion == GR_BI) from manejador.getGrupoActivado();
		
		etiqueta : Etiqueta();
        conversacion : Conversacion();
        comportamiento : ComportamientoAgenteConversacionUsuario();
        
        filtro : String ((equals("Nombre_persona") == true) || (equals("Evento") == true) || (equals("Busqueda") == true)) from etiqueta.getTipo();
    then
    	System.out.println("REGLA BUSCAR IMAGENES CON DIVERSOS FILTROS EJECUTADA");
end