//created on: 24-ago-2018
package photoBot.Drools.Reglas

//list any import classes here.
import photoBot.OpenCV.*;
import photoBot.Drools.*;
import photoBot.Gate.*;
import photoBot.Agentes.Comportamiento.*;
import photoBot.Imagen.*;


//declare any global variables here
global java.lang.Integer GR_BI;
global java.lang.Integer GR_PU;

/*rule "Solicitud de busqueda de todas las imagenes"
	salience 15
	when
		manejador : ManejadorReglas();
        grupoActivacion : Integer(grupoActivacion == GR_PU) from manejador.getGrupoActivado();
		
		etiqueta : Etiqueta();
        conversacion : Conversacion();
        comportamiento : ComportamientoAgenteConversacionUsuario();
        
        tipo_b : String (equals("Busqueda") == true) from etiqueta.getTipo();
    then
    	comportamiento.bot_solicitudBuscarTodasImagenes();  
    	
    	manejador.setGrupoActivado(ConstantesComportamiento.GRUPO_ESPERA_PETICION_USUARIO);
		update(manejador);
		
		System.out.println("REGLA BUSCAR TODAS LAS IMAGENES EJECUTADA");
end
*/

rule "Solicitud peticion busqueda imagenes"
salience 90
	no-loop true
	lock-on-active true
	when
		manejador : ManejadorReglas();
        grupoActivacion : Integer(grupoActivacion == GR_PU) from manejador.getGrupoActivado();
		
		etiqueta : Etiqueta();
        conversacion : Conversacion();
        comportamiento : ComportamientoAgenteConversacionUsuario();
        
        tipo_b : String (equals("Busqueda") == true) from etiqueta.getTipo();
    then
    	
    	comportamiento.solicitarInicializacionListaFiltros();
    	manejador.setGrupoActivado(ConstantesComportamiento.GRUPO_BUSCAR_IMAGEN);
		update(manejador);
		
		System.out.println("REGLA SOLICITUD PETICION BUSQUEDA IMAGENES EJECUTADA" + "--" + manejador.getGrupoActivado());
end

rule "Obtener filtro fecha"
salience 80
	when
		manejador : ManejadorReglas();
        grupoActivacion : Integer(grupoActivacion == GR_BI) from manejador.getGrupoActivado();
		
		etiqueta : Etiqueta();
        conversacion : Conversacion();
        comportamiento : ComportamientoAgenteConversacionUsuario();
        
        filtro : String ((equals("FechaTipo1") == true) || 
	        (equals("FechaTipo2") == true) || 
	        (equals("FechaTipo3") == true) || 
	        (equals("FechaTipo4") == true) || 
	        (equals("FechaTipo5") == true) || 
	        (equals("FechaTipo6") == true) || 
	        (equals("FechaTipo7") == true) ||
	        (equals("FechaCompuestaTipo1") == true) || 
	        (equals("FechaCompuestaTipo2") == true) || 
	        (equals("FechaCompuestaTipo3") == true) || 
	        (equals("FechaCompuestaTipo4") == true) || 
	        (equals("FechaCompuestaTipo7") == true) || 
	        (equals("FechaTipo8") == true)) from etiqueta.getTipo();
    then
    	comportamiento.bot_enviarFiltroFecha(etiqueta);
    	System.out.println("REGLA OBTENER FILTRO FECHA EJECUTADA" + "--" + manejador.getGrupoActivado());
end

rule "Obtener filtro evento"
salience 80
	when
		manejador : ManejadorReglas();
        grupoActivacion : Integer(grupoActivacion == GR_BI) from manejador.getGrupoActivado();
		
		etiqueta : Etiqueta();
        conversacion : Conversacion();
        comportamiento : ComportamientoAgenteConversacionUsuario();
        
        filtro : String (equals("Evento") == true) from etiqueta.getTipo();
    then
    	comportamiento.bot_enviarFiltroEvento(etiqueta);
    	System.out.println("REGLA OBTENER FILTRO EVENTO EJECUTADA" + "--" + manejador.getGrupoActivado());
end

rule "Obtener filtro Persona"
salience 80
	when
		manejador : ManejadorReglas();
        grupoActivacion : Integer(grupoActivacion == GR_BI) from manejador.getGrupoActivado();
		
		etiqueta : Etiqueta();
        conversacion : Conversacion();
        comportamiento : ComportamientoAgenteConversacionUsuario();
        
        filtro : String (equals("Nombre_persona") == true) from etiqueta.getTipo();
    then
    	comportamiento.bot_enviarFiltroPersona(etiqueta);
    	System.out.println("REGLA OBTENER FILTRO PERSONA EJECUTADA" + "--" + manejador.getGrupoActivado());
end

rule "Buscar imagen con filtros"
salience 70
	activation-group "Buscar"
	when
		manejador : ManejadorReglas();
        grupoActivacion : Integer(grupoActivacion == GR_BI) from manejador.getGrupoActivado();
		
		etiqueta : Etiqueta();
        conversacion : Conversacion();
        comportamiento : ComportamientoAgenteConversacionUsuario();
        
        tipo_b : String (equals("Busqueda") == true) from etiqueta.getTipo();
    then
    	
		comportamiento.bot_buscarImagenesFiltros();
		manejador.setGrupoActivado(ConstantesComportamiento.GRUPO_ESPERA_PETICION_USUARIO);
		update(manejador);
		System.out.println("REGLA BUSCAR IMAGENES CON FILTROS EJECUTADA" + "--" + manejador.getGrupoActivado());
end